[versions]
# Version of Kotlin Gradle Plugin used for compilation.
palantir-version = "2.86.0"

[libraries]

palantir = { module = "com.palantir.javaformat:palantir-java-format", version.ref = "palantir-version" }
